version: '3.7'

services:
  elasticsearch:
    container_name: es-cluster
    image: elasticsearch:7.14.2
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - 9200:9200

  kibana:
    image: kibana:7.14.2
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
